INSERT INTO universita (nome, citta_sede) VALUES
('Universita politecnica delle Marche', 'Ancona'),
('Università degli Studi della Valle d\'Aosta', 'Aosta'),
('Università degli Studi di Bari', 'Bari'),
('Politecnico di Bari', 'Bari'),
('Università LUM \"Jean Monnet"\', 'Bari'),
('Università degli Studi di Benevento - Sannio', 'Benevento'),
('Università degli Studi di Bergamo', 'Bergamo'),
('Università degli Studi di Bologna', 'Bologna'),
('Libera Università di Bolzano', 'Bolzano'),
('Università degli Studi di Brescia', 'Brescia'),
('Università degli Studi di Cagliari', 'Cagliari'),
('Università degli Studi di Camerino', 'Camerino'),
('Università degli Studi del Molise', 'Campobasso'),
('Università degli Studi di Cassino e Lazio Meridionale', 'Cassino'),
('Università Cattaneo - LIUC Castellanza', 'Castellanza'),
('Università degli Studi di Catania', 'Catania'),
('Università degli Studi di Catanzaro', 'Catanzaro'),
('Università degli Studi di Chieti e Pescara', 'Chieti'),
('Università degli Studi della Calabria', 'Cosenza'),
('Università Kore di Enna', 'Enna'),
('Università degli Studi di Ferrara', 'Ferrara'),
('Università degli Studi di Firenze', 'Firenze'),
('Università degli Studi di Foggia', 'Foggia'),
('Università degli Studi di Genova', 'Genova'),
('Università degli Studi dell\'Aquila', 'L\'Aquila'),
('Università degli Studi del Salento', 'Lecce'),
('Scuola IMT di Lucca', 'Lucca'),
('Università degli Studi di Macerata', 'Macerata'),
('Università degli Studi di Messina', 'Messina'),
('Università degli Studi di Milano', 'Milano'),
('Università degli Studi Milano Bicocca', 'Milano'),
('Università Cattolica del Sacro Cuore Milano', 'Milano'),
('Politecnico di Milano', 'Milano'),
('Università Bocconi di Milano', 'Milano'),
('Humanitas University Milano', 'Milano'),
('Università IULM Milano', 'Milano'),
('San Raffaele Milano', 'Milano'),
('Università degli Studi di Modena e Reggio Emilia', 'Modena'),
('Università degli Studi di Napoli Federico II', 'Napoli'),
('Università degli Studi della Campania Vanvitelli', 'Napoli'),
('Università degli Studi L\'Orientale di Napoli', 'Napoli'),
('Università degli Studi Suor Orsola Benincasa Napoli', 'Napoli'),
('Università Telematica Leonardo Da Vinci', 'Online'),
('Università Telematica E-Campus', 'Online'),
('Università Telematica Giustino Fortunato', 'Online'),
('Università Telematica Guglielmo Marconi', 'Online'),
('Università Telematica San Raffaele Roma', 'Online'),
('Università Telematica UniNettuno', 'Online'),
('Università Telematica IUL', 'Online'),
('Università Telematica Pegaso', 'Online'),
('Università Telematica Unitelma Sapienza', 'Online'),
('Università Telematica Unicusano', 'Online'),
('Università Telematica Universitas Mercatorum', 'Online'),
('Università degli Studi di Padova', 'Padova'),
('Università degli Studi di Palermo', 'Palermo'),
('Università degli Studi di Parma', 'Parma'),
('Università degli Studi di Pavia', 'Pavia'),
('IUSS di Pavia', 'Pavia'),
('Università degli Studi di Perugia', 'Perugia'),
('Università degli Studi Stranieri Perugia', 'Perugia'),
('Università degli Studi di Pisa', 'Pisa'),
('Scuola Superiore Normale di Pisa', 'Pisa'),
('Scuola Superiore Sant\'Anna di Pisa', 'Pisa'),
('Università degli Studi della Basilicata', 'Potenza'),
('Università Mediterranea di Reggio Calabria', 'Reggio Calabria'),
('Università degli Stranieri di Reggio Calabria', 'Reggio Calabria'),
('Università Europea di Roma', 'Roma'),
('Università del Foro Italico di Roma', 'Roma'),
('Università degli Studi La Sapienza di Roma', 'Roma'),
('Università degli Studi di Tor Vergata di Roma', 'Roma'),
('Università degli Studi Roma Tre', 'Roma'),
('Università Campus Bio-Medico di Roma', 'Roma'),
('Università degli Studi LUISS Guido Carli di Roma', 'Roma'),
('Università degli Studi Internazionali di Roma UNINT', 'Roma'),
('Libera Università Maria SS Assunta LUMSA Roma', 'Roma'),
('UniCamillus', 'Roma'),
('Link Campus', 'Roma'),
('Università degli Studi di Salerno', 'Salerno'),
('Università degli Studi di Sassari', 'Sassari'),
('Università degli Studi di Siena', 'Siena'),
('Università degli Studi degli Stranieri di Siena', 'Siena'),
('Università degli Studi di Teramo', 'Teramo'),
('Università degli Studi di Torino', 'Torino'),
('Politecnico di Torino', 'Torino'),
('Università degli Studi di Trento', 'Trento'),
('Università degli Studi di Trieste', 'Trieste'),
('Università degli Studi Sissa Trieste', 'Trieste'),
('Università degli Studi di Udine', 'Udine'),
('Università degli Studi di Urbino Carlo Bo', 'Urbino'),
('Università degli Studi dell\'Insubria', 'Varese'),
('Università degli Studi Cà Foscari di Venezia', 'Venezia'),
('Università degli Studi del Piemonte Orientale', 'Vercelli'),
('Università degli Studi di Verona', 'Verona'),
('Università degli Studi della Tuscia', 'Viterbo');