INSERT INTO materia (nome) VALUES

('Antropologia culturale'),
('Etnologia'),
('Antropologia sociale'),
('Antropologia visiva'),
('Antropologia del corpo e della salute'),
('Antropologia delle religioni'),
('Antropologia economica'),
('Antropologia politica'),
('Etnografia'),
('Metodi della ricerca etnografica'),
('Storia dell''antropologia'),
('Antropologia urbana'),
('Antropologia del genere'),
('Antropologia dell''alimentazione'),
('Teorie antropologiche'),
('Antropologia dello sviluppo'),
('Semiotica della cultura'),
('Sociologia dei processi culturali'),
('Linguistica antropologica'),
('Antropologia cognitiva'),
('Etnomusicologia'),
('Studi postcoloniali'),
('Antropologia delle migrazioni'),
('Folklore e tradizioni popolari'),
('Antropologia del turismo'),
('Teoria della cultura'),

('Archeologia classica'),
('Archeologia medievale'),
('Archeologia preistorica'),
('Archeologia orientale'),
('Metodologia della ricerca archeologica'),
('Topografia antica'),
('Epigrafia greca'),
('Epigrafia latina'),
('Numismatica'),
('Paletnologia'),
('Archeologia subacquea'),
('Archeozoologia'),
('Archeobotanica'),
('Geoarcheologia'),
('Archeologia dei paesaggi'),
('Storia dell''arte antica'),
('Museologia e museografia'),
('Tecniche di scavo'),
('Rilievo e documentazione dei beni archeologici'),
('Informatica applicata all''archeologia'),
('Archeologia romana'),
('Archeologia greca'),
('Conservazione e restauro dei reperti'),
('Antropologia fisica'),
('Paleopatologia'),
('Storia delle religioni antiche'),

('Progettazione del paesaggio'),
('Ecologia del paesaggio'),
('Storia dei giardini'),
('Botanica applicata al paesaggio'),
('Urbanistica e pianificazione'),
('Disegno del paesaggio'),
('Tecniche costruttive del verde'),
('Geomorfologia'),
('Pedologia'),
('Idraulica del paesaggio'),
('Valutazione di impatto ambientale'),
('GIS e cartografia'),
('Progettazione partecipata'),
('Legislazione ambientale e paesaggistica'),
('Agronomia ornamentale'),
('Arboricoltura ornamentale'),
('Gestione del verde urbano'),
('Architettura del paesaggio storico'),
('Restauro dei giardini storici'),
('Sostenibilità ambientale'),

('Progettazione architettonica 1'),
('Progettazione architettonica 2'),
('Progettazione architettonica 3'),
('Composizione architettonica'),
('Storia dell''architettura 1'),
('Storia dell''architettura 2'),
('Storia dell''architettura contemporanea'),
('Disegno e rilievo'),
('Geometria descrittiva'),
('Fondamenti di matematica per architettura'),
('Fisica tecnica'),
('Scienza delle costruzioni'),
('Tecnica delle costruzioni'),
('Tecnologia dell''architettura'),
('Impianti tecnici'),
('Urbanistica'),
('Restauro architettonico'),
('Progettazione strutturale'),
('Estimo e valutazione immobiliare'),
('Progettazione urbana'),
('Architettura degli interni'),
('Tecnologie per la sostenibilità'),
('Progettazione bioclimatica'),
('Materiali per l''edilizia'),
('Legislazione urbanistica'),
('Progettazione del dettaglio costruttivo'),
('Laboratorio di costruzione'),
('Cultura tecnologica della progettazione'),
('Diritto dell''edilizia'),
('Rappresentazione digitale dell''architettura'),

('Archivistica generale'),
('Archivistica speciale'),
('Biblioteconomia'),
('Storia del libro e dell''editoria'),
('Paleografia latina'),
('Codicologia'),
('Diplomatica'),
('Informatica documentaria'),
('Gestione dei sistemi informativi'),
('Catalogazione bibliografica'),
('Classificazione e indicizzazione'),
('Basi di dati per l''informazione'),
('Diritto dell''informazione'),
('Conservazione e restauro del documento'),
('Storia delle biblioteche'),
('Storia degli archivi'),
('Documentazione e information retrieval'),
('Legislazione archivistica e bibliotecaria'),
('Archivi digitali'),
('Open access e editoria digitale'),

('Storia dell''arte medievale'),
('Storia dell''arte moderna'),
('Storia dell''arte contemporanea'),
('Museologia'),
('Archeologia e storia dell''arte greca e romana'),
('Storia medievale'),
('Storia moderna'),
('Letteratura italiana'),
('Lingua e cultura latina'),
('Lingua e cultura greca'),
('Legislazione dei beni culturali'),
('Economia della cultura'),
('Marketing culturale'),
('Informatica per i beni culturali'),
('Fondamenti di storia'),
('Estetica'),
('Elementi di archivistica e biblioteconomia'),

('Biologia cellulare avanzata'),
('Biologia molecolare avanzata'),
('Genetica avanzata'),
('Biochimica avanzata'),
('Fisiologia avanzata'),
('Ecologia avanzata'),
('Bioinformatica'),
('Genomica'),
('Proteomica'),
('Neurobiologia'),
('Biologia dello sviluppo'),
('Immunologia'),
('Microbiologia avanzata'),
('Biologia evoluzionistica'),
('Tecniche biomolecolari'),
('Tossicologia'),
('Biologia marina'),
('Zoologia avanzata'),
('Botanica avanzata'),
('Statistica per la biologia'),

('Biologia cellulare'),
('Biologia molecolare'),
('Genetica'),
('Biochimica'),
('Microbiologia'),
('Chimica organica'),
('Chimica generale e inorganica'),
('Matematica per le biotecnologie'),
('Fisica per le biotecnologie'),
('Fisiologia'),
('Immunologia di base'),
('Enzimologia'),
('Tecnologie del DNA ricombinante'),
('Colture cellulari'),
('Bioreattori'),
('Biochimica applicata'),
('Statistica biologica'),
('Laboratorio di biotecnologie'),

('Biotecnologie vegetali'),
('Genetica agraria avanzata'),
('Miglioramento genetico delle piante'),
('Biotecnologie microbiche agrarie'),
('Fisiologia vegetale avanzata'),
('Genomica agraria'),
('Bioinformatica agraria'),
('Tecnologie del DNA ricombinante nelle piante'),
('Patologia vegetale avanzata'),
('Controllo biologico'),
('Biotecnologie per la qualità degli alimenti'),
('Diritto e bioetica delle biotecnologie'),
('Legislazione agraria'),
('Agrobiotecnologie ambientali'),
('Entomologia agraria avanzata'),

('Biochimica industriale'),
('Microbiologia industriale'),
('Ingegneria biochimica'),
('Bioreattori industriali'),
('Downstream processing'),
('Fermentazione industriale'),
('Enzimologia industriale'),
('Biotecnologie ambientali'),
('Bioraffinerie'),
('Metabolic engineering'),
('Genomica funzionale industriale'),
('Normativa per le biotecnologie industriali'),
('Biosicurezza'),
('Scale-up industriale'),
('Tecnologie per i biopolimeri'),

('Biotecnologie farmaceutiche'),
('Farmacologia molecolare'),
('Biotecnologie diagnostiche'),
('Terapia genica'),
('Biotecnologie vaccinali'),
('Biotecnologie veterinarie'),
('Oncologia molecolare'),
('Immunotecnologie'),
('Produzione di farmaci biotecnologici'),
('Bioetica e biosicurezza medica'),
('Regolamentazione farmaceutica'),
('Nanotecnologie in medicina'),
('Medicina rigenerativa'),
('Trapianti e xenotrapianti'),
('Diagnostica molecolare avanzata'),

('Storia dell''architettura'),
('Rilievo e documentazione del costruito'),
('Teoria del restauro'),
('Tecnologie per il restauro'),
('Diagnostica del costruito'),
('Materiali e tecniche storiche costruttive'),
('Conservazione dell''ambiente costruito'),
('Legislazione per il restauro'),
('Strutture per il restauro'),
('Consolidamento strutturale'),
('Restauro urbano'),
('Paesaggio storico urbano'),
('Archeologia dell''architettura'),
('Cantiere di restauro'),

('Teoria e storia del restauro'),
('Chimica per la conservazione'),
('Fisica per la conservazione'),
('Diagnostica per i beni culturali'),
('Restauro di dipinti su tela e tavola'),
('Restauro di affreschi'),
('Restauro di sculture'),
('Restauro di materiali cartacei'),
('Restauro di materiali fotografici'),
('Restauro di manufatti tessili'),
('Restauro di metalli'),
('Restauro di ceramiche e vetri'),
('Biologia per la conservazione'),
('Microbiologia per i beni culturali'),
('Museografia'),
('Documentazione del bene culturale'),
('Conservazione preventiva'),
('Materiali e prodotti per il restauro'),

('Machine Learning'),
('Deep Learning'),
('Statistica avanzata'),
('Big Data Analytics'),
('Data Mining'),
('Basi di dati avanzate'),
('Programmazione per la Data Science'),
('Visualizzazione dei dati'),
('Natural Language Processing'),
('Computer Vision'),
('Cloud Computing'),
('Probabilità e inferenza statistica'),
('Algebra lineare per la data science'),
('Ottimizzazione'),
('Etica dell''intelligenza artificiale'),
('Business Intelligence'),
('Time Series Analysis'),
('Reti neurali'),
('Reinforcement Learning'),
('Sistemi distribuiti'),

('Fondamenti del design'),
('Disegno tecnico industriale'),
('Storia del design'),
('Ergonomia'),
('Teoria della percezione visiva'),
('Materiali e lavorazioni industriali'),
('Modellazione 3D'),
('Design del prodotto'),
('Design della comunicazione'),
('Prototipazione'),
('Informatica per il design'),
('Marketing del design'),
('Fotografia per il design'),
('Semiotica visiva'),
('Metodologia del progetto'),
('Sostenibilità nel design'),
('Packaging design'),
('Interaction design'),
('User experience design'),

('Chimica farmaceutica 1'),
('Chimica farmaceutica 2'),
('Farmacologia 1'),
('Farmacologia 2'),
('Farmacognosia'),
('Chimica organica 1'),
('Chimica organica 2'),
('Anatomia umana'),
('Microbiologia e virologia'),
('Tecnologia farmaceutica'),
('Farmacoterapia'),
('Chimica analitica'),
('Analisi del farmaco'),
('Botanica farmaceutica'),
('Biochimica clinica'),
('Legislazione farmaceutica'),
('Fisica'),
('Matematica'),
('Statistica per le scienze farmaceutiche'),
('Biofarmacia e farmacocinetica'),

('Letteratura italiana contemporanea'),
('Filologia italiana'),
('Critica del testo'),
('Filologia romanza'),
('Linguistica italiana'),
('Storia della lingua italiana'),
('Letteratura comparata'),
('Teoria della letteratura'),
('Stilistica'),
('Ecdotica'),
('Letteratura italiana del Medioevo e del Rinascimento'),
('Letteratura italiana del Seicento e del Settecento'),
('Letteratura italiana dell''Ottocento'),
('Letteratura italiana del Novecento'),
('Semiotica del testo'),
('Retorica'),
('Informatica umanistica'),
('Lingua e letteratura latina medievale'),

('Filologia greca'),
('Filologia latina'),
('Letteratura greca'),
('Letteratura latina'),
('Storia greca'),
('Storia romana'),
('Papirologia'),
('Epigrafia greca avanzata'),
('Epigrafia latina avanzata'),
('Lingua greca avanzata'),
('Lingua latina avanzata'),
('Storia della filosofia antica'),
('Mitologia classica'),
('Drammaturgia antica'),
('Tradizione classica'),

('Storia della filosofia medievale'),
('Storia della filosofia moderna'),
('Storia della filosofia contemporanea'),
('Logica'),
('Filosofia della scienza'),
('Filosofia morale'),
('Filosofia politica'),
('Epistemologia'),
('Metafisica'),
('Ontologia'),
('Filosofia del linguaggio'),
('Filosofia della mente'),
('Ermeneutica'),
('Etica'),
('Filosofia teoretica'),
('Filosofia della religione'),
('Fenomenologia'),
('Teoria della conoscenza'),

('Matematica finanziaria'),
('Economia dei mercati finanziari'),
('Analisi finanziaria'),
('Gestione del portafoglio'),
('Derivati finanziari'),
('Risk management'),
('Corporate finance'),
('Econometria finanziaria'),
('Finanza aziendale avanzata'),
('Banca e intermediazione finanziaria'),
('Diritto dei mercati finanziari'),
('Macroeconomia avanzata'),
('Microeconomia avanzata'),
('Statistica finanziaria'),
('Finanza comportamentale'),
('Mercati obbligazionari'),
('Private equity e venture capital'),
('Finanza internazionale'),
('Modelli stocastici per la finanza'),
('Regulation e compliance finanziaria'),

('Analisi matematica 1'),
('Analisi matematica 2'),
('Geometria'),
('Fisica 1'),
('Fisica 2'),
('Meccanica analitica'),
('Fisica matematica'),
('Fisica moderna'),
('Fisica quantistica'),
('Relatività'),
('Termodinamica e meccanica statistica'),
('Ottica'),
('Fisica nucleare e subnucleare'),
('Fisica della materia'),
('Fisica computazionale'),
('Laboratorio di fisica 1'),
('Laboratorio di fisica 2'),
('Elettromagnetismo'),
('Meccanica razionale'),
('Astrofisica'),

('Algoritmi e strutture dati'),
('Programmazione 1'),
('Programmazione 2'),
('Architettura degli elaboratori'),
('Sistemi operativi'),
('Basi di dati'),
('Reti di calcolatori'),
('Ingegneria del software'),
('Analisi matematica'),
('Algebra lineare e geometria'),
('Probabilità e statistica'),
('Linguaggi di programmazione'),
('Calcolo numerico'),
('Logica matematica'),
('Sicurezza informatica'),
('Programmazione web'),
('Intelligenza artificiale'),
('Compilatori'),
('Interazione uomo-macchina'),

('Teoria dell''informazione'),
('Semiotica'),
('Giornalismo digitale'),
('Editoria digitale'),
('Marketing editoriale'),
('Comunicazione multimediale'),
('Linguaggi dei media'),
('Sociologia della comunicazione'),
('Scrittura creativa e professionale'),
('Web journalism'),
('Storia del giornalismo'),
('Economia dei media'),
('Media studies'),
('Strategie di comunicazione'),
('Data journalism'),

('Aerodinamica'),
('Propulsione aerospaziale'),
('Strutture aerospaziali'),
('Meccanica del volo'),
('Progettazione aeronautica'),
('Sistemi di guida e controllo'),
('Termodinamica applicata aerospaziale'),
('Fluidodinamica computazionale'),
('Tecnologia aerospaziale'),
('Dinamica del volo spaziale'),
('Navigazione spaziale'),
('Materiali aerospaziali'),
('Resistenza dei materiali aerospaziali'),
('Comunicazioni aerospaziali'),
('Progettazione di sistemi spaziali'),
('Meccanica orbitale'),

('Fisiologia umana'),
('Chimica e biochimica'),
('Biomeccanica'),
('Biofisica'),
('Strumentazione biomedica'),
('Elaborazione di segnali biomedici'),
('Informatica biomedica'),
('Imaging biomedico'),
('Biomateriali'),
('Ingegneria del tessuto'),
('Ingegneria clinica'),
('Modelli matematici in biologia'),
('Elettronica biomedica'),
('Robotica medica'),
('Regolamentazione dispositivi medici'),
('Sicurezza in ambienti sanitari'),
('Tecnologie riabilitative'),

('Chimica fisica'),
('Fondamenti di chimica'),
('Operazioni unitarie 1'),
('Operazioni unitarie 2'),
('Fenomeni di trasporto'),
('Cinetica chimica e reattori'),
('Termodinamica chimica'),
('Impianti chimici'),
('Progettazione di reattori chimici'),
('Controllo dei processi chimici'),
('Simulazione di processi'),
('Sicurezza degli impianti chimici'),
('Ingegneria dell''ambiente'),
('Processi chimici industriali'),
('Fluidodinamica chimica'),
('Catalisi industriale'),
('Chimica verde'),
('Tecnologie per l''energia'),

('Chimica'),
('Geotecnica'),
('Idraulica'),
('Idrologia'),
('Topografia'),
('Infrastrutture viarie'),
('Ponti e strutture speciali'),
('Ingegneria sismica'),
('Progettazione strutturale in cemento armato'),
('Progettazione strutturale in acciaio'),
('Costruzioni idrauliche'),
('Urbanistica tecnica'),
('Impianti civili'),
('Economia e gestione dei lavori pubblici'),
('Diritto e legislazione delle opere pubbliche'),

('Scienza dei materiali'),
('Metallurgia'),
('Materiali polimerici'),
('Materiali ceramici'),
('Materiali compositi'),
('Proprietà meccaniche dei materiali'),
('Proprietà elettriche e magnetiche dei materiali'),
('Caratterizzazione dei materiali'),
('Tecnologie di lavorazione dei materiali'),
('Trattamenti termici'),
('Corrosione e protezione'),
('Materiali per l''energia'),
('Nanomateriali'),
('Materiali funzionali avanzati'),

('Controlli automatici'),
('Sistemi di controllo avanzati'),
('Robotica'),
('Identificazione dei sistemi'),
('Controllo ottimo'),
('Sistemi meccatronici'),
('Visione artificiale'),
('Reti di Petri'),
('Automazione industriale'),
('Sistemi embedded'),
('Controllo predittivo'),
('Logica programmabile'),
('Sensoristica avanzata'),
('Sistemi multi-agente'),
('Controllo di sistemi ibridi'),

('Circuiti elettrici'),
('Elettronica analogica'),
('Elettronica digitale'),
('Segnali e sistemi'),
('Comunicazioni digitali'),
('Elaborazione numerica dei segnali'),
('Microelettronica'),
('Sistemi di elaborazione'),
('Teoria dell''informazione e codici'),
('Fondamenti di informatica'),
('Probabilità e statistica per l''ingegneria'),

('Sicurezza sul lavoro'),
('Prevenzione incendi'),
('Gestione del rischio industriale'),
('Valutazione del rischio'),
('Sicurezza chimica'),
('Igiene industriale'),
('Normativa sulla sicurezza'),
('Ergonomia della sicurezza'),
('Sicurezza degli impianti'),
('Protezione civile'),
('Gestione delle emergenze'),
('Fattori umani e sicurezza'),

('Trasmissione numerica'),
('Antenne e propagazione'),
('Reti di telecomunicazione'),
('Elaborazione di segnali avanzata'),
('Protocolli di comunicazione'),
('Wireless communications'),
('Reti mobili'),
('Ottica per telecomunicazioni'),
('Teoria delle code'),
('Sicurezza nelle telecomunicazioni'),
('Internet of Things'),
('Sistemi radar e sonar'),
('Comunicazioni satellitari'),
('5G e reti future'),

('Macchine elettriche'),
('Impianti elettrici'),
('Elettrotecnica'),
('Azionamenti elettrici'),
('Sistemi elettrici di potenza'),
('Alta tensione'),
('Elettronica di potenza'),
('Compatibilità elettromagnetica'),
('Illuminotecnica'),
('Sistemi di distribuzione dell''energia'),
('Energia rinnovabile elettrica'),
('Smart grid'),
('Progettazione di impianti elettrici civili e industriali'),

('Elettronica analogica avanzata'),
('Elettronica digitale avanzata'),
('Microelectronica'),
('Progettazione di circuiti integrati'),
('Dispositivi elettronici'),
('Sistemi embedded avanzati'),
('Elettronica per le comunicazioni'),
('Optoelettronica'),
('MEMS e nanotecnologie elettroniche'),
('Test e affidabilità elettronica'),
('Prototipazione elettronica'),

('Termodinamica applicata avanzata'),
('Trasmissione del calore'),
('Macchine a fluido'),
('Centrali elettriche'),
('Energia nucleare'),
('Reattori nucleari'),
('Sicurezza nucleare'),
('Energie rinnovabili'),
('Efficienza energetica'),
('Sistemi energetici'),
('Combustione'),
('Radioprotezione'),
('Fisica del reattore'),
('Gestione dei rifiuti radioattivi'),

('Organizzazione aziendale'),
('Gestione della produzione'),
('Ricerca operativa'),
('Economia e gestione delle imprese'),
('Logistica industriale'),
('Qualità e affidabilità'),
('Gestione dei progetti'),
('Marketing industriale'),
('Supply chain management'),
('Lean manufacturing'),
('Analisi dei costi'),
('Sistemi informativi aziendali'),
('Strategia aziendale'),
('Economia industriale'),
('Gestione dell''innovazione'),
('Finanza aziendale'),
('Statistica per l''ingegneria gestionale'),

('Algoritmi avanzati'),
('Architetture avanzate degli elaboratori'),
('Ingegneria del software avanzata'),
('Sistemi operativi avanzati'),
('Reti avanzate'),
('Sicurezza informatica avanzata'),
('Intelligenza artificiale avanzata'),
('Sistemi distribuiti avanzati'),
('Cloud e edge computing'),
('Blockchain'),
('Sviluppo mobile'),
('DevOps e continuous integration'),
('Virtualizzazione'),
('Cybersecurity avanzata'),

('Meccanica applicata alle macchine'),
('Costruzione di macchine 1'),
('Costruzione di macchine 2'),
('Meccanica dei fluidi'),
('Tecnologia meccanica'),
('Impianti industriali'),
('Metodi agli elementi finiti'),
('Tribologia'),
('Dinamica e vibrazioni'),
('Metallurgia meccanica'),
('Manutenzione industriale'),
('Progettazione di sistemi meccanici'),
('Robotica industriale'),
('Trasmissione del calore meccanica'),
('Lavorazioni per asportazione di truciolo'),
('Lavorazioni per deformazione plastica'),

('Teoria della nave'),
('Architettura navale'),
('Propulsione navale'),
('Strutture navali'),
('Idrodinamica navale'),
('Sistemi di bordo'),
('Resistenza della nave'),
('Manovrabilità'),
('Progettazione navale'),
('Impianti navali'),
('Normativa marittima'),
('Offshore engineering'),
('Acustica subacquea'),

('Ingegneria sanitaria-ambientale'),
('Gestione dei rifiuti'),
('Ingegneria idraulica ambientale'),
('Bonifica dei siti contaminati'),
('Valutazione di impatto ambientale avanzata'),
('Depurazione delle acque'),
('Trattamento aria'),
('Legislazione ambientale'),
('Geotecnica ambientale'),
('Telerilevamento'),
('Modelli matematici per l''ambiente'),
('Energia e ambiente'),
('Pianificazione ambientale'),

('Letteratura italiana 1'),
('Letteratura italiana 2'),
('Lingua e letteratura latina'),
('Lingua e letteratura greca'),
('Storia contemporanea'),
('Lingua straniera 1'),
('Fondamenti di glottologia'),
('Paleografia'),
('Retorica e poetica'),
('Filosofia della letteratura'),

('Lingua inglese 1'),
('Lingua inglese 2'),
('Lingua francese'),
('Lingua spagnola'),
('Lingua tedesca'),
('Lingua portoghese'),
('Letteratura inglese'),
('Letteratura francese'),
('Letteratura spagnola'),
('Letteratura tedesca'),
('Glottologia'),
('Linguistica generale'),
('Traduzione'),
('Cultura e civiltà angloamericana'),
('Storia della lingua inglese'),
('Storia della lingua francese'),
('Linguistica comparata'),
('Filologia germanica'),

('Lingua araba 1'),
('Lingua araba 2'),
('Lingua cinese 1'),
('Lingua cinese 2'),
('Lingua giapponese 1'),
('Lingua giapponese 2'),
('Lingua hindi'),
('Lingua swahili'),
('Lingua persiana'),
('Lingua turca'),
('Letteratura araba'),
('Letteratura cinese'),
('Letteratura giapponese'),
('Storia e cultura del mondo islamico'),
('Storia e cultura dell''Asia orientale'),
('Storia dell''Africa'),
('Antropologia culturale afroasiatica'),
('Linguistica afroasiatica'),

('Letteratura inglese avanzata'),
('Letteratura americana'),
('Letteratura francese avanzata'),
('Letteratura spagnola avanzata'),
('Letteratura tedesca avanzata'),
('Linguistica inglese avanzata'),
('Linguistica francese avanzata'),
('Traduzione letteraria'),
('Letteratura postcoloniale'),
('Teoria della letteratura avanzata'),
('Letteratura comparata avanzata'),
('Critica letteraria'),
('Letteratura russa'),
('Cinema e letteratura'),
('Digital humanities per le letterature'),

('Linguistica teorica avanzata'),
('Fonologia avanzata'),
('Morfologia avanzata'),
('Sintassi avanzata'),
('Semantica avanzata'),
('Pragmatica'),
('Sociolinguistica'),
('Linguistica computazionale'),
('Linguistica acquisizionale'),
('Psicolinguistica'),
('Tipologia linguistica'),
('Neurolinguistica'),
('Linguistica storica'),
('Dialettologia'),
('Analisi del discorso'),

('Diritto privato'),
('Diritto costituzionale'),
('Diritto penale'),
('Diritto amministrativo'),
('Diritto civile 1'),
('Diritto civile 2'),
('Diritto commerciale'),
('Diritto del lavoro'),
('Diritto internazionale'),
('Diritto dell''Unione Europea'),
('Diritto processuale civile'),
('Diritto processuale penale'),
('Diritto tributario'),
('Diritto romano'),
('Istituzioni di diritto privato'),
('Filosofia del diritto'),
('Storia del diritto italiano'),
('Storia del diritto romano'),
('Diritto ecclesiastico'),
('Diritto della navigazione'),
('Criminologia'),
('Medicina legale'),
('Diritto fallimentare'),
('Diritto assicurativo'),
('Diritto bancario'),

('Analisi matematica 3'),
('Geometria 1'),
('Geometria 2'),
('Algebra'),
('Probabilità'),
('Analisi numerica'),
('Topologia'),
('Geometria differenziale'),
('Equazioni differenziali'),
('Analisi funzionale'),
('Algebra superiore'),
('Teoria dei numeri'),
('Matematica discreta'),
('Calcolo delle probabilità avanzato'),
('Statistica matematica'),
('Istituzioni di analisi superiore'),

('Anatomia umana 1'),
('Anatomia umana 2'),
('Fisiologia 1'),
('Fisiologia 2'),
('Biologia e genetica'),
('Istologia ed embriologia'),
('Patologia generale'),
('Farmacologia'),
('Medicina interna 1'),
('Medicina interna 2'),
('Chirurgia generale 1'),
('Chirurgia generale 2'),
('Pediatria'),
('Ginecologia e ostetricia'),
('Psichiatria'),
('Neurologia'),
('Cardiologia'),
('Pneumologia'),
('Gastroenterologia'),
('Nefrologia'),
('Endocrinologia'),
('Reumatologia'),
('Oncologia'),
('Ortopedia e traumatologia'),
('Urologia'),
('Dermatologia e venereologia'),
('Oftalmologia'),
('Otorinolaringoiatria'),
('Radiologia'),
('Anestesiologia e rianimazione'),
('Igiene e medicina preventiva'),
('Medicina del lavoro'),
('Medicina di urgenza ed emergenza'),
('Chirurgia toracica'),
('Chirurgia vascolare'),
('Neurochirurgia'),
('Ematologia'),
('Immunologia clinica'),

('Anatomia veterinaria 1'),
('Anatomia veterinaria 2'),
('Fisiologia veterinaria'),
('Biochimica veterinaria'),
('Microbiologia veterinaria'),
('Parassitologia veterinaria'),
('Patologia generale veterinaria'),
('Farmacologia veterinaria'),
('Clinica medica veterinaria'),
('Clinica chirurgica veterinaria'),
('Medicina degli animali da compagnia'),
('Medicina degli animali da reddito'),
('Medicina degli animali selvatici'),
('Ispezione degli alimenti di origine animale'),
('Igiene e legislazione degli alimenti'),
('Anatomia patologica veterinaria'),
('Tossicologia veterinaria'),
('Medicina legale veterinaria'),
('Ostetricia veterinaria'),
('Zootecnia'),
('Diagnostica per immagini veterinaria'),
('Anestesiologia veterinaria'),

('Psicologia generale'),
('Psicologia dello sviluppo'),
('Psicologia sociale'),
('Psicologia clinica'),
('Psicologia del lavoro e delle organizzazioni'),
('Psicologia dinamica'),
('Neuropsicologia'),
('Psicobiologia'),
('Metodologia della ricerca psicologica'),
('Statistica per la psicologia'),
('Psicologia della personalità'),
('Psicologia cognitiva'),
('Psicopatologia'),
('Psicologia delle emozioni'),
('Fondamenti di biologia e fisiologia'),
('Teoria e tecnica dei test'),
('Psicologia dell''educazione'),
('Psicologia di comunità'),
('Psicologia della salute'),
('Tecniche di intervento psicologico'),
('Fondamenti di neuroscienze'),
('Psicoterapie'),
('Assessment psicologico'),

('Zoologia'),
('Botanica'),
('Ecologia'),
('Fisiologia animale'),
('Fisiologia vegetale'),
('Anatomia comparata'),
('Palaeontologia'),
('Sistematica biologica'),
('Matematica e statistica per la biologia'),
('Fisica per la biologia'),
('Chimica biologica'),

('Chimica generale e inorganica 1'),
('Chimica generale e inorganica 2'),
('Chimica fisica 1'),
('Chimica fisica 2'),
('Chimica analitica 1'),
('Chimica analitica 2'),
('Chimica industriale'),
('Chimica computazionale'),
('Spettroscopia'),
('Cristallografia'),
('Chimica dei polimeri'),
('Chimica dei materiali'),
('Chimica supramolecolare'),
('Chimica bioorganica'),
('Laboratorio di chimica organica'),
('Laboratorio di chimica inorganica'),
('Laboratorio di chimica analitica'),
('Matematica per la chimica'),

('Psicologia cognitiva avanzata'),
('Neuroscienze cognitive'),
('Linguistica cognitiva'),
('Intelligenza artificiale cognitiva'),
('Modelli computazionali della cognizione'),
('Percezione e azione'),
('Memoria e apprendimento'),
('Attenzione e controllo'),
('Embodied cognition'),
('Neuroimaging cognitivo'),
('Pragmatica cognitiva'),
('Scienze cognitive dello sviluppo'),
('Logica e ragionamento'),
('Tecnologie cognitive'),

('Sociologia della devianza'),
('Psicologia criminale'),
('Vittimologia'),
('Criminologia clinica'),
('Tecniche investigative'),
('Criminalistica'),
('Sociologia della polizia'),
('Sicurezza pubblica e privata'),
('Criminalità organizzata'),
('Devianza minorile'),
('Politiche criminali'),
('Statistica criminologica'),

('Econometria avanzata'),
('Economia pubblica avanzata'),
('Economia internazionale avanzata'),
('Economia industriale avanzata'),
('Economia del lavoro'),
('Economia della crescita'),
('Economia monetaria avanzata'),
('Teoria dei giochi avanzata'),
('Economia dell''informazione'),
('Economia dello sviluppo'),
('Economia ambientale'),
('Economia comportamentale'),
('Storia del pensiero economico'),
('Metodi quantitativi avanzati'),

('Teoria e tecniche della comunicazione di massa'),
('Linguistica e comunicazione'),
('Storia dei media'),
('Psicologia della comunicazione'),
('Comunicazione politica'),
('Comunicazione pubblicitaria'),
('Relazioni pubbliche'),
('Comunicazione interculturale'),
('Nuovi media e comunicazione digitale'),
('Diritto dell''informazione e della comunicazione'),
('Scrittura giornalistica'),
('Radio e televisione'),
('Fondamenti di informatica per la comunicazione'),

('Pedagogia generale'),
('Didattica generale'),
('Psicologia dell''età evolutiva'),
('Letteratura per l''infanzia'),
('Didattica della matematica'),
('Didattica dell''italiano'),
('Didattica delle scienze naturali'),
('Didattica della storia e geografia'),
('Didattica delle lingue straniere'),
('Laboratorio di didattica delle arti'),
('Laboratorio di educazione motoria'),
('Musica e didattica della musica'),
('Educazione speciale'),
('Pedagogia interculturale'),
('Tecnologie educative'),
('Metodologia della ricerca educativa'),
('Diritto scolastico e legislazione'),
('Sociologia dell''educazione'),
('Antropologia culturale per la formazione'),
('Laboratorio di tirocinio'),
('Lingua inglese per la formazione primaria'),

('Botanica sistematica avanzata'),
('Geologia'),
('Biologia della conservazione'),
('Biogeografia'),
('Gestione della fauna selvatica'),
('Limnologia'),
('Biologia marina avanzata'),
('Sistemi informativi geografici'),
('Paleontologia avanzata'),
('Climalologia'),
('Etologia'),
('Conservazione della biodiversità'),
('Valutazione ambientale'),

('Biochimica della nutrizione'),
('Fisiologia della nutrizione'),
('Nutrizione clinica'),
('Scienza degli alimenti'),
('Dietetica'),
('Patologie nutrizionali'),
('Tecnologia alimentare avanzata'),
('Igiene degli alimenti'),
('Epidemiologia nutrizionale'),
('Nutrizione nelle diverse fasi della vita'),
('Nutrizione nello sport'),
('Nutrizione in oncologia'),
('Legislazione alimentare'),
('Valutazione nutrizionale'),
('Psicologia dell''alimentazione'),

('Scienza politica'),
('Teoria politica'),
('Sistemi politici comparati'),
('Relazioni internazionali'),
('Sociologia politica'),
('Storia delle dottrine politiche'),
('Economia politica'),
('Metodologia delle scienze sociali'),
('Politiche pubbliche'),
('Geopolitica'),
('Studi europei'),
('Partiti e sistemi elettorali'),
('Storia delle istituzioni politiche'),

('Teoria e metodologia dell''allenamento sportivo'),
('Psicologia dello sport'),
('Sociologia dello sport'),
('Medicina dello sport'),
('Diritto sportivo'),
('Economia dello sport'),
('Atletica leggera'),
('Giochi sportivi'),
('Attività motorie per la salute'),
('Attività motorie adattate'),
('Pedagogia dello sport'),
('Teoria e pratica delle attività motorie preventive'),
('Management sportivo'),
('Marketing dello sport'),
('Teoria e tecnica delle discipline sportive'),
('Test e misurazione in ambito motorio'),
('Chinesiterapia'),

('Agronomia generale'),
('Coltivazioni erbacee'),
('Coltivazioni arboree'),
('Patologia vegetale'),
('Entomologia agraria'),
('Chimica agraria'),
('Economia e politica agraria'),
('Meccanica agraria'),
('Sistemi informativi territoriali in agricoltura'),
('Idraulica agraria'),
('Miglioramento genetico vegetale'),
('Gestione delle risorse naturali'),
('Orticoltura e floricoltura'),
('Agroforestry'),
('Contabilità e gestione aziendale agraria'),
('Irrigazione e drenaggio'),

('Microbiologia degli alimenti'),
('Chimica degli alimenti'),
('Tecnologia dei cereali e derivati'),
('Tecnologia della carne'),
('Tecnologia del latte e derivati'),
('Tecnologia dei prodotti ittici'),
('Tecnologia dell''olio e dei grassi'),
('Tecnologia delle bevande'),
('Conservazione degli alimenti'),
('Imballaggio e packaging alimentare'),
('Qualità degli alimenti'),
('Analisi sensoriale'),
('Igiene e sicurezza alimentare'),
('Biochimica degli alimenti'),
('Marketing dei prodotti alimentari'),
('Enologia'),
('Oleochimica'),

('Chimica farmaceutica applicata'),
('Farmacologia applicata'),
('Tecnologie farmaceutiche applicate'),
('Botanica farmaceutica applicata'),
('Cosmetologia'),
('Analisi del farmaco applicata'),
('Chimica medicinale'),
('Farmacovigilanza'),
('Biofarmacia'),
('Laboratorio di galenica'),

('Fisica computazionale avanzata'),
('Fisica della materia condensata'),
('Fisica nucleare applicata'),
('Fisica medica'),
('Astrofisica e cosmologia'),
('Fisica dei plasmi'),
('Ottica avanzata'),
('Fisica subnucleare'),
('Strumentazione fisica avanzata'),
('Biofisica avanzata'),

('Geologia strutturale'),
('Petrografia'),
('Paleontologia'),
('Geochimica'),
('Mineralogia'),
('Sedimentologia'),
('Stratigrafia'),
('Vulcanologia'),
('Geofisica applicata'),
('Idrogeologia'),
('Geologia applicata'),
('Geologia tecnica'),
('Cartografia geologica'),
('Telerilevamento geologico'),
('Georischi'),
('Micropaleontologia'),

('Programmazione avanzata'),
('Cybersecurity'),
('Machine learning applicato'),
('Sistemi informativi'),
('Sviluppo web avanzato'),
('Progettazione di applicazioni mobile'),
('Internet of Things applicato'),
('Architetture software'),
('Testing del software'),

('Economia politica 1'),
('Economia politica 2'),
('Macroeconomia'),
('Microeconomia'),
('Matematica per l''economia 1'),
('Matematica per l''economia 2'),
('Statistica economica'),
('Econometria'),
('Economia pubblica'),
('Economia internazionale'),
('Economia monetaria'),
('Teoria dei giochi'),
('Politica economica'),
('Storia economica'),
('Scienza delle finanze'),
('Ragioneria'),

('Economia aziendale'),
('Ragioneria generale e applicata'),
('Statistica'),
('Marketing'),
('Gestione delle risorse umane'),
('Bilancio e principi contabili'),
('Revisione aziendale'),
('Strategia e politica aziendale'),
('Economia dei mercati e degli intermediari finanziari'),
('Economia e gestione delle imprese internazionali'),
('Analisi di bilancio'),
('Business planning'),

('Filosofia teoretica avanzata'),
('Ontologia avanzata'),
('Epistemologia avanzata'),
('Etica avanzata'),
('Estetica avanzata'),
('Filosofia politica avanzata'),
('Filosofia del linguaggio avanzata'),
('Storia della filosofia moderna avanzata'),
('Storia della filosofia contemporanea avanzata'),
('Ermeneutica avanzata'),
('Filosofia analitica'),
('Metafisica avanzata'),
('Fenomenologia avanzata'),
('Logica avanzata'),
('Bioetica'),

('Diritto pubblico'),
('Sociologia del diritto'),
('Informatica giuridica'),
('Mediazione e risoluzione delle controversie'),
('Diritto bancario e finanziario'),
('Diritto internazionale privato'),

('Scienze infermieristiche avanzate'),
('Management infermieristico'),
('Ricerca infermieristica'),
('Infermieristica in area critica avanzata'),
('Infermieristica in salute mentale avanzata'),
('Farmacologia avanzata'),
('Bioetica clinica'),
('Diritto sanitario'),
('Epidemiologia clinica'),
('Metodologia della ricerca in area sanitaria'),
('Educazione terapeutica'),
('Scienze ostetriche avanzate'),
('Perinatologia'),
('Ginecologia oncologica'),
('Leadership in ambito sanitario'),

('Pedagogia generale avanzata'),
('Pedagogia speciale avanzata'),
('Didattica avanzata'),
('Pedagogia interculturale avanzata'),
('Pedagogia familiare'),
('Pedagogia della marginalità sociale'),
('Psicologia dello sviluppo avanzata'),
('Metodologia della ricerca educativa avanzata'),
('Tecnologie educative avanzate'),
('Formazione degli adulti avanzata'),
('Gestione delle organizzazioni educative'),
('Progettazione educativa e formativa'),
('Neuroscienze e educazione'),
('Counseling educativo'),
('Politiche educative'),

('Storia delle relazioni internazionali'),
('Organizzazioni internazionali'),
('Diplomazia e negoziato'),

('Statistica 1'),
('Statistica 2'),
('Inferenza statistica'),
('Analisi multivariata'),
('Statistica computazionale'),
('Modelli statistici lineari'),
('Serie storiche'),
('Statistica bayesiana'),
('Statistica per la qualità'),
('Statistica attuariale'),
('Analisi dei dati campionari'),
('Biostatistica'),
('Statistica demografica'),
('Statistica sociale'),
('Teoria del rischio'),
('Statistica per la ricerca sperimentale'),

('Storia antica'),
('Storia dell''Europa'),
('Storia degli Stati Uniti'),
('Storia dell''Asia'),
('Storia dell''America Latina'),
('Storia sociale'),
('Storia culturale'),
('Storia delle donne e di genere'),
('Paleografia e archivistica'),
('Metodologia della ricerca storica'),
('Storiografia'),
('Storia delle istituzioni'),
('Storia della mentalità'),
('Storia delle religioni'),
('Storia locale'),

('Crittografia'),
('Sicurezza delle reti avanzata'),
('Penetration testing'),
('Malware analysis'),
('Digital forensics'),
('Sicurezza dei sistemi operativi'),
('Sicurezza applicativa'),
('Cloud security'),
('Sicurezza IoT'),
('Threat intelligence'),
('Incident response'),
('Cybersecurity governance e compliance'),
('Sicurezza dei protocolli'),
('Secure software development'),
('Reverse engineering'),
('Blockchain e sicurezza'),

('Sociologia generale'),
('Teoria sociologica'),
('Metodologia della ricerca sociale'),
('Sociologia della famiglia'),
('Sociologia del lavoro'),
('Sociologia urbana'),
('Sociologia economica'),
('Sociologia della salute'),
('Sociologia delle migrazioni'),
('Tecnica della ricerca sociale'),
('Analisi dei dati qualitativi'),
('Politiche sociali'),
('Sociologia ambientale'),

('Storia dell''arte medievale avanzata'),
('Storia dell''arte moderna avanzata'),
('Storia dell''arte contemporanea avanzata'),
('Iconografia e iconologia'),
('Critica d''arte'),
('Museologia e museografia avanzata'),
('Storia della fotografia'),
('Storia del cinema e delle arti visive'),
('Teoria dell''arte'),
('Arte e digitale'),
('Mercato dell''arte'),
('Conservazione preventiva avanzata'),
('Catalogazione dei beni culturali'),
('Curatela e allestimento'),
('Public art'),

('Diritto dell''Unione Europea avanzato'),
('Politiche dell''Unione Europea'),
('Economia europea'),
('Storia dell''integrazione europea'),
('Istituzioni europee'),
('Politica estera e di sicurezza comune'),
('Fondi europei e politiche di coesione'),
('Lingue per l''Europa'),
('Governance multilivello'),
('Democrazia e partecipazione in Europa'),

('Teorie della comunicazione avanzate'),
('Semiotica avanzata'),
('Comunicazione e media digitali avanzata'),
('Retorica contemporanea'),
('Teoria dell''argomentazione'),
('Comunicazione interculturale avanzata'),
('Comunicazione politica avanzata'),
('Analisi del discorso avanzata'),
('Etica della comunicazione'),

('Traduzione tecnica e scientifica'),
('Traduzione giuridica'),
('Traduzione letteraria avanzata'),
('Interpretazione consecutiva'),
('Interpretazione simultanea'),
('Traduzione audiovisiva'),
('Localizzazione software'),
('Terminologia e terminografia'),
('Traduzione automatica e post-editing'),
('Revisione della traduzione'),
('Lingua inglese avanzata per la traduzione'),
('Lingua francese avanzata per la traduzione'),
('Lingua spagnola avanzata per la traduzione'),
('Lingua tedesca avanzata per la traduzione'),
('Etica del traduttore'),

('Tecnica urbanistica'),
('Pianificazione territoriale'),
('Diritto urbanistico'),
('Economia urbana e regionale'),
('Sistemi informativi geografici avanzati'),
('Recupero urbano'),
('Mobilità e trasporti'),
('Valutazione ambientale strategica'),
('Gestione del rischio territoriale'),
('Infrastrutture urbane'),
('Cartografia avanzata'),
('Smart city e governo digitale del territorio'),
('Storia della città e del territorio'),
('Partecipazione e governance del territorio'),

('Scienze infermieristiche generali'),
('Infermieristica clinica in area medica'),
('Infermieristica clinica in area chirurgica'),
('Infermieristica in area materno-infantile'),
('Infermieristica in salute mentale e psichiatria'),
('Infermieristica in area critica'),
('Basi anatomo-fisiologiche del corpo umano'),
('Farmacologia infermieristica'),
('Metodologia clinica'),
('Etica e bioetica infermieristica'),
('Legislazione sanitaria e deontologia'),
('Scienze umane e sociali'),
('Epidemiologia e prevenzione'),
('Informatica infermieristica'),
('Tirocinio professionale'),

('Fisioterapia generale'),
('Neuroriabilitazione'),
('Riabilitazione ortopedica'),
('Riabilitazione respiratoria'),
('Terapia occupazionale'),
('Logopedia'),
('Ortottica e assistenza oftalmologica'),
('Audiologia e audioprotesi'),
('Tecnica della neuro e psicomotricità dell''età evolutiva'),
('Scienze del movimento'),
('Anatomia funzionale'),
('Fisiologia clinica'),
('Patologie per la riabilitazione'),
('Metodologia riabilitativa'),
('Tirocinio professionale riabilitativo'),

('Tecniche di laboratorio biomedico'),
('Tecniche radiologiche'),
('Tecniche di fisiopatologia cardiocircolatoria'),
('Tecniche di neurofisiopatologia'),
('Tecniche di dietetica'),
('Tecniche audioprotesiche'),
('Tecniche ortopediche'),
('Tecniche di perfusione cardiovascolare'),
('Igiene applicata alle professioni sanitarie'),
('Anatomia patologica tecnica'),
('Fisica medica applicata'),
('Tirocinio professionale tecnico sanitario'),

('Igiene e sanità pubblica'),
('Sicurezza ambienti di vita e lavoro'),
('Epidemiologia'),
('Tecniche di prevenzione ambienti e luoghi di lavoro'),
('Vigilanza e ispezione degli alimenti'),
('Igiene degli alimenti e della nutrizione'),
('Prevenzione delle malattie infettive'),
('Normativa igienistico-sanitaria'),
('Tirocinio professionale della prevenzione'),

('Management sanitario'),
('Organizzazione e gestione dei servizi sanitari'),
('Diritto sanitario avanzato'),
('Bioetica avanzata'),
('Ricerca e EBM avanzata'),
('Formazione e didattica in area sanitaria'),
('Qualità e sicurezza nelle cure'),
('Epidemiologia clinica avanzata'),
('Sistemi sanitari comparati'),

('Selvicoltura'),
('Dendrologia'),
('Assestamento forestale'),
('Ecologia forestale'),
('Difesa del suolo'),
('Idrologia forestale'),
('Tecnologie forestali'),
('Economia forestale'),
('Pianificazione forestale'),
('Incendi boschivi'),
('Arboricoltura da legno'),
('Gestione delle aree protette'),
('Riforestazione'),
('Fauna selvatica e caccia'),
('Legislazione forestale'),

('Zootecnia generale'),
('Zootecnia speciale'),
('Nutrizione animale'),
('Miglioramento genetico animale'),
('Gestione delle aziende zootecniche'),
('Produzioni animali'),
('Etologia ed ecologia animale'),
('Fisiologia degli animali domestici'),
('Biotecnologie riproduttive'),
('Economia zootecnica'),
('Legislazione zootecnica'),
('Qualità dei prodotti di origine animale'),
('Patologie del bestiame'),
('Acquacoltura'),

('Fondamenti del servizio sociale'),
('Teoria e metodologia del servizio sociale'),
('Diritto di famiglia e dei minori'),
('Sociologia delle organizzazioni'),
('Psicologia clinica e di comunità'),
('Servizio sociale con i minori'),
('Servizio sociale con gli anziani'),
('Servizio sociale in ambito penale'),
('Servizio sociale e disabilità'),
('Progettazione sociale'),
('Welfare state e politiche del lavoro'),
('Terzo settore e volontariato'),
('Tirocinio di servizio sociale'),
('Supervisione e consulenza nel servizio sociale'),

('Teoria delle relazioni internazionali'),
('Diritto internazionale avanzato'),
('Storia delle relazioni internazionali avanzata'),
('Organizzazioni internazionali avanzata'),
('Politica estera comparata'),
('Sicurezza internazionale'),
('Geopolitica avanzata'),
('Diritto internazionale dei diritti umani'),
('Economia dello sviluppo internazionale'),
('Governance globale'),
('Negoziazione internazionale'),
('Studi strategici'),
('Lingua straniera per le relazioni internazionali'),

('Storia della musica 1'),
('Storia della musica 2'),
('Storia della musica contemporanea'),
('Analisi musicale'),
('Musicologia sistematica'),
('Paleografia musicale'),
('Teoria musicale avanzata'),
('Musica e società'),
('Conservazione dei beni musicali'),
('Discografia e archivi musicali'),
('Informatica musicale'),
('Semiologia musicale'),
('Musica da camera - storia e analisi'),
('Opera lirica - storia e analisi'),

('Anatomia del cavo orale'),
('Fisiologia della masticazione'),
('Materiali dentari'),
('Clinica odontostomatologica'),
('Chirurgia orale'),
('Ortodonzia'),
('Parodontologia'),
('Endodonzia'),
('Protesi dentaria'),
('Implantologia'),
('Odontologia conservativa'),
('Pedodonzia'),
('Radiologia dentomaxillofacciale'),
('Medicina orale'),
('Gnatologia'),

('Economia del turismo avanzata'),
('Marketing turistico avanzato'),
('Gestione delle imprese turistiche'),
('Turismo sostenibile'),
('Turismo culturale'),
('Pianificazione e gestione delle destinazioni'),
('Politiche del turismo'),
('Diritto del turismo'),
('Digital tourism'),
('Turismo enogastronomico'),
('Revenue management'),
('Hospitality management'),
('Turismo accessibile'),
('Gestione degli eventi'),

('Economia del turismo'),
('Marketing turistico'),
('Storia e cultura del turismo'),
('Geografia del turismo'),
('Sociologia del turismo'),
('Lingue per il turismo 1'),
('Lingue per il turismo 2'),
('Informatica per il turismo'),
('Economia e gestione delle imprese ricettive'),
('Beni culturali e turismo'),
('Legislazione turistica'),
('Ecologia del turismo'),

('Scienza dell''amministrazione'),
('Scienza della politica'),
('Sociologia dell''organizzazione'),
('Informatica pubblica'),
('E-government'),
('Statistica pubblica'),
('Management pubblico'),
('Politiche pubbliche avanzate'),
('Analisi delle politiche pubbliche'),
('Diritto dell''Unione Europea applicato'),
('Comunicazione pubblica'),

('Storia della pedagogia'),
('Educazione degli adulti'),
('Metodologie dell''intervento educativo'),
('Tecnologie dell''educazione'),
('Pedagogia speciale'),
('Diritto minorile'),
('Animazione socioculturale'),
('Teoria dell''organizzazione educativa'),

('Lingua inglese per la comunicazione internazionale'),
('Lingua francese per la cooperazione'),
('Lingua spagnola per la comunicazione internazionale'),
('Lingua araba per la cooperazione'),
('Lingua cinese per la cooperazione'),
('Comunicazione istituzionale internazionale'),
('Cooperazione allo sviluppo'),
('Diritto internazionale umanitario'),
('Organizzazioni non governative'),
('Tecniche di negoziazione internazionale'),

('Informatica umanistica avanzata'),
('Digital humanities'),
('Basi di dati per le discipline umanistiche'),
('Linguistica computazionale avanzata'),
('Edizione digitale dei testi'),
('Sistemi informativi culturali'),
('Analisi testuale computazionale'),
('Web semantico e ontologie'),
('Digitalizzazione e conservazione digitale'),
('Visualizzazione dei dati umanistici'),
('Programmazione per le umanistiche'),

('Analisi funzionale avanzata'),
('Equazioni differenziali avanzate'),
('Metodi numerici avanzati'),
('Fisica matematica avanzata'),
('Meccanica dei continui'),
('Fluidodinamica matematica'),
('Modelli stocastici'),
('Ottimizzazione avanzata'),
('Geometria differenziale avanzata'),
('Teoria dei sistemi dinamici'),
('Calcolo delle variazioni'),

('Sismologia'),
('Geodesia'),
('Geomagnetismo'),
('Geofisica dell''interno della Terra'),
('Oceanografia fisica'),
('Meteorologia avanzata'),
('Gravimetria'),
('Prospezione geofisica'),
('Tomografia sismica'),
('Fisica dell''atmosfera'),
('Remote sensing geofisico'),

('Geografia umana avanzata'),
('Geografia fisica avanzata'),
('GIS avanzato'),
('Geografia regionale'),
('Climatologia avanzata'),
('Biogeografia avanzata'),
('Geografia rurale'),
('Gestione del territorio avanzata'),
('Geostatistica'),
('Telerilevamento avanzato'),

('Astrofisica avanzata'),
('Cosmologia'),
('Astrofisica delle galassie'),
('Fisica stellare'),
('Astrofisica relativistica'),
('Astronomia osservativa'),
('Astrofisica delle alte energie'),
('Radioastronomia'),
('Strumentazione astronomica'),
('Astrobiologia'),
('Pianeti e sistemi planetari'),

('Chimica dei materiali culturali'),
('Fisica applicata ai beni culturali'),
('Biologia applicata ai beni culturali'),
('Diagnostica dei materiali'),
('Fondamenti di conservazione e restauro'),
('Legislazione dei beni culturali applicata'),
('Mineralogia applicata'),
('Archeometria'),
('Tecniche fotografiche per i beni culturali'),

('Lingua inglese per la mediazione'),
('Lingua francese per la mediazione'),
('Lingua spagnola per la mediazione'),
('Lingua tedesca per la mediazione'),
('Lingua araba per la mediazione'),
('Teoria della traduzione'),
('Tecniche di traduzione'),
('Interpretazione di trattativa'),
('Linguistica per la mediazione'),
('Diritto per la mediazione linguistica'),
('Economia per la mediazione linguistica'),
('Cultura e civiltà per la mediazione'),

('Chimica industriale avanzata'),
('Catalisi avanzata'),
('Chimica dei polimeri avanzata'),
('Elettrochimica industriale'),
('Chimica delle superfici'),
('Sicurezza chimica industriale'),
('Impianti chimici avanzati'),
('Chimica verde avanzata'),
('Materiali avanzati'),
('Nanotecnologie chimiche'),

('Navigazione aerea'),
('Navigazione marittima'),
('Meteorologia nautica'),
('Sistemi di navigazione elettronica'),
('Sicurezza marittima e aerea'),
('Meccanica navale'),
('Gestione del traffico aereo e marittimo'),
('Comunicazioni per la navigazione'),
('Logistica dei trasporti'),

('Fenomenologia della religione'),
('Sociologia della religione'),
('Psicologia della religione'),
('Filosofia della religione avanzata'),
('Testi sacri comparati'),
('Ebraismo'),
('Islamologia'),
('Buddhismo'),
('Induismo'),
('Cristianesimo e storia della chiesa'),
('Nuovi movimenti religiosi'),
('Etica delle religioni'),

('Teoria del cinema avanzata'),
('Analisi filmologica'),
('Storia del teatro avanzata'),
('Produzione cinematografica'),
('Produzione televisiva e multimediale'),
('Drammaturgia avanzata'),
('Regia teatrale e cinematografica'),
('Tecnologie per la produzione multimediale'),
('Critica teatrale e cinematografica'),
('Marketing culturale e dello spettacolo'),
('Diritto dello spettacolo'),
('Sceneggiatura'),
('Effetti speciali e VFX'),
('Sound design'),
('Distribuzione e promozione culturale'),

('Economia ambientale avanzata'),
('Economia dei beni culturali avanzata'),
('Politica economica ambientale'),
('Valutazione economica dei beni culturali'),
('Economia della sostenibilità'),
('Mercato dell''arte avanzato'),
('Green economy'),
('Finanza sostenibile'),
('Gestione dei musei e dei siti culturali'),
('Economia circolare'),

('Criminologia avanzata'),
('Psicologia criminale avanzata'),
('Sociologia della devianza avanzata'),
('Politiche criminali avanzate'),
('Analisi delle scene del crimine'),
('Criminalità organizzata avanzata'),
('Intelligence e sicurezza'),
('Diritto penale avanzato'),
('Vittimologia avanzata'),
('Criminalità informatica'),
('Terrorismo e sicurezza internazionale'),

('Ecologia applicata'),
('Chimica ambientale'),
('Fisica ambientale'),
('Geologia ambientale'),
('Biologia della conservazione avanzata'),
('Analisi e monitoraggio ambientale'),
('Tecnologie di risanamento ambientale'),
('Gestione sostenibile del territorio'),
('Impatto ambientale dei processi industriali'),
('Diritto ambientale'),
('Economia dell''ambiente avanzata'),
('Gestione delle risorse idriche'),

('Lingua inglese (B1)'),
('Lingua inglese (B2)'),
('Lingua inglese (C1)'),
('Prova finale / Tesi di laurea'),
('Tirocinio formativo'),
('Laboratorio professionalizzante'),
('Abilità informatiche e telematiche'),
('Altre attività formative'),
('Attività seminariali');