INSERT INTO facolta (nome) VALUES
('Antropologia culturale ed etnologia (LM-1)'),
('Archeologia (LM-2)'),
('Architettura del paesaggio (LM-3)'),
('Architettura e ingegneria edile-architettura (LM-4)'),
('Architettura e ingegneria edile-architettura (quinquennale) (LM-4 c.u.)'),
('Archivistica e biblioteconomia (LM-5)'),
('Beni culturali (L-1)'),
('Biologia (LM-6)'),
('Biotecnologie (L-2)'),
('Biotecnologie agrarie (LM-7)'),
('Biotecnologie industriali (LM-8)'),
('Biotecnologie mediche, veterinarie e farmaceutiche (LM-9)'),
('Classe di abilitazione A033 - Tecnologia (Abil.)'),
('Classe di abilitazione A059 - Matematica e scienze nella scuola secondaria di I grado (Abil.)'),
('Conservazione dei beni architettonici e ambientali (LM-10)'),
('Conservazione e restauro dei beni culturali (L-43 / LM-11)'),
('Data Science (LM-91)'),
('Design (L-4)'),
('Diagnostica per la conservazione dei beni culturali (LM-11)'),
('Discipline delle arti figurative, della musica, dello spettacolo e della moda (L-3)'),
('Disegno industriale (L-4)'),
('Farmacia e farmacia industriale (LM-13)'),
('Filologia moderna (LM-14)'),
('Filologia moderna (abilitazione A043) (LM-14)'),
('Filologia, letterature e storia dell\'antichità (LM-15)'),
('Filosofia (L-5)'),
('Finanza (LM-16)'),
('Fisica (L-30)'),
('Geografia (L-6)'),
('Informatica (L-31)'),
('Informazione e sistemi editoriali (LM-19)'),
('Ingegneria aerospaziale e astronautica (LM-20)'),
('Ingegneria biomedica (L-8 / LM-21)'),
('Ingegneria chimica (L-9 / LM-22)'),
('Ingegneria civile (L-7 / LM-23)'),
('Ingegneria civile e ambientale (L-7)'),
('Ingegneria dei materiali (L-9 / LM-53)'),
('Ingegneria dei sistemi edilizi (LM-24)'),
('Ingegneria dell\'automazione (L-8 / LM-25)'),
('Ingegneria dell\'informazione (L-8)'),
('Ingegneria della sicurezza (LM-26)'),
('Ingegneria delle telecomunicazioni (LM-27)'),
('Ingegneria elettrica (L-9 / LM-28)'),
('Ingegneria elettronica (L-8 / LM-29)'),
('Ingegneria energetica e nucleare (LM-30)'),
('Ingegneria gestionale (L-9 / LM-31)'),
('Ingegneria industriale (L-9)'),
('Ingegneria informatica (L-8 / LM-32)'),
('Ingegneria meccanica (L-9 / LM-33)'),
('Ingegneria navale (L-9 / LM-34)'),
('Ingegneria per l\'ambiente e il territorio (LM-35)'),
('Lettere (L-10)'),
('Lingue e culture moderne (L-11)'),
('Lingue e letterature dell\'Africa e dell\'Asia (L-11 / LM-36)'),
('Lingue e letterature moderne europee e americane (LM-37)'),
('Lingue e letterature moderne europee e americane (abilitazione A045) (LM-37)'),
('Lingue moderne per la comunicazione e la cooperazione internazionale (LM-38)'),
('Linguistica (LM-39)'),
('Magistrali in giurisprudenza (LMG-01)'),
('Matematica (L-35)'),
('Mediazione linguistica (L-12)'),
('Medicina e chirurgia (LM-41)'),
('Medicina veterinaria (LM-42)'),
('Metodologie informatiche per le discipline umanistiche (LM-43)'),
('Modellistica matematico-fisica per l\'ingegneria (LM-44)'),
('Musicologia e beni musicali (LM-45)'),
('Musicologia e beni musicali (abilitazione A032) (LM-45)'),
('Odontoiatria e protesi dentaria (LM-46)'),
('Organizzazione e gestione dei servizi per lo sport e le attività motorie (LM-47)'),
('Pianificazione territoriale urbanistica e ambientale (L-21 / LM-48)'),
('Professioni sanitarie della prevenzione (L/SNT4)'),
('Professioni sanitarie della riabilitazione (L/SNT2)'),
('Professioni sanitarie tecniche (L/SNT3)'),
('Professioni sanitarie, infermieristiche e professione sanitaria ostetrica (L/SNT1)'),
('Professioni tecniche agrarie, alimentari e forestali (L-P02)'),
('Professioni tecniche industriali e dell\'informazione (L-P03)'),
('Professioni tecniche per l\'edilizia e il territorio (L-P01)'),
('Progettazione e gestione dei sistemi turistici (LM-49)'),
('Programmazione e gestione dei servizi educativi (LM-50)'),
('Psicologia (L-24 / LM-51)'),
('Relazioni internazionali (LM-52)'),
('Scienza e ingegneria dei materiali (LM-53)'),
('Scienze della formazione primaria (LM-85 bis)'),
('Scienze biologiche (L-13)'),
('Scienze chimiche (L-27 / LM-54)'),
('Scienze cognitive (LM-55)'),
('Scienze criminologiche applicate all\'investigazione e alla sicurezza (L-14)'),
('Scienze criminologiche e della sicurezza (L-14 / LM-62)'),
('Scienze dei beni culturali (L-1)'),
('Scienze dei Materiali (L-30 / LM-53)'),
('Scienze dei servizi giuridici (L-14)'),
('Scienze del servizio sociale (L-39)'),
('Scienze del turismo (L-15)'),
('Scienze dell\'amministrazione (L-16)'),
('Scienze dell\'amministrazione e dell\'organizzazione (L-16)'),
('Scienze dell\'architettura (L-17)'),
('Scienze dell\'architettura e dell\'ingegneria edile (L-23)'),
('Scienze dell\'architettura e dell\'ingegneria edile - Ciclo Unico (LM-4 c.u.)'),
('Scienze dell\'economia (LM-56)'),
('Scienze dell\'economia e della gestione aziendale (L-18)'),
('Scienze dell\'educazione degli adulti e della formazione continua (LM-57)'),
('Scienze dell\'educazione e della formazione (L-19)'),
('Scienze dell\'universo (LM-58)'),
('Scienze della comunicazione (L-20)'),
('Scienze della comunicazione pubblica, d\'impresa e pubblicità (LM-59)'),
('Scienze della difesa e della sicurezza (L-DS / LM-DS)'),
('Scienze della Formazione Primaria - Quadriennale (V.O.)'),
('Scienze della mediazione linguistica (L-12)'),
('Scienze della natura (L-32 / LM-60)'),
('Scienze della nutrizione umana (LM-61)'),
('Scienze della pianificazione territoriale, urbanistica, paesaggistica e ambientale (L-21)'),
('Scienze della politica (L-36 / LM-62)'),
('Scienze della Terra (L-34)'),
('Scienze delle attivita motorie e sportive (L-22)'),
('Scienze delle professioni sanitarie della prevenzione (LM/SNT4)'),
('Scienze delle professioni sanitarie tecniche (LM/SNT3)'),
('Scienze delle pubbliche amministrazioni (LM-63)'),
('Scienze delle religioni (LM-64)'),
('Scienze dello spettacolo e produzione multimediale (LM-65)'),
('Scienze e tecniche dell\'edilizia (L-23)'),
('Scienze e tecniche delle attività motorie preventive e adattate (LM-67)'),
('Scienze e tecniche delle attività motorie preventive e adattate (abilitazione A030) (LM-67)'),
('Scienze e tecniche dello sport (LM-68)'),
('Scienze e tecniche dello sport (abilitazione A030) (LM-68)'),
('Scienze e tecniche psicologiche (L-24)'),
('Scienze e tecnologie agrarie (L-25 / LM-69)'),
('Scienze e tecnologie agrarie e forestali (L-25)'),
('Scienze e tecnologie agrarie, agroalimentari e forestali (L-25)'),
('Scienze e tecnologie alimentari (L-26 / LM-70)'),
('Scienze e tecnologie chimiche (L-27)'),
('Scienze e tecnologie della chimica industriale (L-27 / LM-71)'),
('Scienze e tecnologie della navigazione (L-28 / LM-72)'),
('Scienze e tecnologie delle arti figurative, della musica, dello spettacolo e della moda (L-3)'),
('Scienze e tecnologie farmaceutiche (L-29)'),
('Scienze e tecnologie fisiche (L-30)'),
('Scienze e tecnologie forestali ed ambientali (L-25 / LM-73)'),
('Scienze e tecnologie geologiche (L-34 / LM-74)'),
('Scienze e tecnologie informatiche (L-31)'),
('Scienze e tecnologie per l\'ambiente e il territorio (L-32 / LM-75)'),
('Scienze e tecnologie per l\'ambiente e la natura (L-32)'),
('Scienze e tecnologie zootecniche e delle produzioni animali (L-38 / LM-86)'),
('Scienze economiche (L-33)'),
('Scienze economiche e sociali della gastronomia (L-Gastr)'),
('Scienze economiche per l\'ambiente e la cultura (LM-76)'),
('Scienze economico-aziendali (LM-77)'),
('Scienze filosofiche (LM-78)'),
('Scienze geofisiche (LM-79)'),
('Scienze geografiche (LM-80)'),
('Scienze geologiche (L-34)'),
('Scienze Giuridiche (L-14)'),
('Scienze giuridiche - Quinquennale (LMG-01)'),
('Scienze infermieristiche e ostetriche (LM/SNT1)'),
('Scienze matematiche (L-35)'),
('Scienze pedagogiche (LM-85)'),
('Scienze per la conservazione dei beni culturali (L-43)'),
('Scienze per la cooperazione allo sviluppo (L-37 / LM-81)'),
('Scienze politiche e delle relazioni internazionali (L-36)'),
('Scienze riabilitative delle professioni sanitarie (LM/SNT2)'),
('Scienze sociali per la cooperazione, lo sviluppo e la pace (L-37)'),
('Scienze sociologiche (L-40)'),
('Scienze statistiche (L-41 / LM-82)'),
('Scienze statistiche attuariali e finanziarie (LM-83)'),
('Scienze storiche (L-42 / LM-84)'),
('Scienze zootecniche e tecnologie animali (L-38)'),
('Scienze, culture e politiche della gastronomia (L-Gastr)'),
('Servizio sociale (L-39)'),
('Servizio sociale e politiche sociali (LM-87)'),
('Sicurezza informatica (LM-66)'),
('Sociologia (L-40 / LM-88)'),
('Sociologia e ricerca sociale (LM-88)'),
('Specialistiche in antropologia culturale ed etnologia (1/S)'),
('Specialistiche in archeologia (2/S)'),
('Specialistiche in architettura del paesaggio (3/S)'),
('Specialistiche in architettura e ingegneria edile (4/S)'),
('Specialistiche in archivistica e biblioteconomia (5/S)'),
('Specialistiche in biologia (6/S)'),
('Specialistiche in biotecnologie agrarie (7/S)'),
('Specialistiche in biotecnologie industriali (8/S)'),
('Specialistiche in biotecnologie mediche, veterinarie e farmaceutiche (9/S)'),
('Specialistiche in conservazione dei beni architettonici e ambientali (10/S)'),
('Specialistiche in conservazione dei beni scientifici e della civilta industriale (11/S)'),
('Specialistiche in conservazione e restauro del patrimonio storico-artistico (12/S)'),
('Specialistiche in editoria, comunicazione multimediale e giornalismo (13/S)'),
('Specialistiche in farmacia e farmacia industriale (14/S)'),
('Specialistiche in filologia e letterature dell\'antichita (15/S)'),
('Specialistiche in filologia moderna (16/S)'),
('Specialistiche in filosofia e storia della scienza (17/S)'),
('Specialistiche in filosofia teoretica, morale, politica ed estetica (18/S)'),
('Specialistiche in finanza (19/S)'),
('Specialistiche in fisica (20/S)'),
('Specialistiche in geografia (21/S)'),
('Specialistiche in giurisprudenza (22/S)'),
('Specialistiche in informatica (23/S)'),
('Specialistiche in informatica per le discipline umanistiche (24/S)'),
('Specialistiche in ingegneria aerospaziale e astronautica (25/S)'),
('Specialistiche in ingegneria biomedica (26/S)'),
('Specialistiche in ingegneria chimica (27/S)'),
('Specialistiche in ingegneria civile (28/S)'),
('Specialistiche in ingegneria dell\'automazione (29/S)'),
('Specialistiche in ingegneria delle telecomunicazioni (30/S)'),
('Specialistiche in ingegneria elettrica (31/S)'),
('Specialistiche in ingegneria elettronica (32/S)'),
('Specialistiche in ingegneria energetica e nucleare (33/S)'),
('Specialistiche in ingegneria gestionale (34/S)'),
('Specialistiche in ingegneria informatica (35/S)'),
('Specialistiche in ingegneria meccanica (36/S)'),
('Specialistiche in ingegneria navale (37/S)'),
('Specialistiche in ingegneria per l\'ambiente e il territorio (38/S)'),
('Specialistiche in interpretariato di conferenza (39/S)'),
('Specialistiche in lingua e cultura italiana (40/S)'),
('Specialistiche in lingue e letterature afroasiatiche (41/S)'),
('Specialistiche in lingue e letterature moderne euroamericane (42/S)'),
('Specialistiche in lingue straniere per la comunicazione internazionale (43/S)'),
('Specialistiche in linguistica (44/S)'),
('Specialistiche in matematica (45/S)'),
('Specialistiche in medicina e chirurgia (46/S)'),
('Specialistiche in medicina veterinaria (47/S)'),
('Specialistiche in metodi per l\'analisi valutativa dei sistemi complessi (48/S)'),
('Specialistiche in metodi per la ricerca empirica nelle scienze sociali (49/S)'),
('Specialistiche in modellistica matematico-fisica per l\'ingegneria (50/S)'),
('Specialistiche in musicologia e beni musicali (51/S)'),
('Specialistiche in odontoiatria e protesi dentaria (52/S)'),
('Specialistiche in organizzazione e gestione dei servizi per lo sport e le attivita motorie (53/S)'),
('Specialistiche in pianificazione territoriale urbanistica e ambientale (54/S)'),
('Specialistiche in progettazione e gestione dei sistemi turistici (55/S)'),
('Specialistiche in programmazione e gestione dei servizi educativi e formativi (56/S)'),
('Specialistiche in programmazione e gestione delle politiche e dei servizi sociali (57/S)'),
('Specialistiche in psicologia (58/S)'),
('Specialistiche in pubblicita e comunicazione d\'impresa (59/S)'),
('Specialistiche in relazioni internazionali (60/S)'),
('Specialistiche in scienza e ingegneria dei materiali (61/S)'),
('Specialistiche in scienze chimiche (62/S)'),
('Specialistiche in scienze cognitive (63/S)'),
('Specialistiche in scienze dell\'economia (64/S)'),
('Specialistiche in scienze dell\'educazione degli adulti e della formazione continua (65/S)'),
('Specialistiche in scienze dell\'universo (66/S)'),
('Specialistiche in scienze della comunicazione sociale e istituzionale (67/S)'),
('Specialistiche in scienze della natura (68/S)'),
('Specialistiche in scienze della nutrizione umana (69/S)'),
('Specialistiche in scienze della politica (70/S)'),
('Specialistiche in scienze delle pubbliche amministrazioni (71/S)'),
('Specialistiche in scienze delle religioni (72/S)'),
('Specialistiche in scienze dello spettacolo e della produzione multimediale (73/S)'),
('Specialistiche in scienze e gestione delle risorse rurali e forestali (74/S)'),
('Specialistiche in scienze e tecnica dello sport (75/S)'),
('Specialistiche in scienze e tecniche delle attivita motorie preventive e adattative (76/S)'),
('Specialistiche in scienze e tecnologie agrarie (77/S)'),
('Specialistiche in scienze e tecnologie agroalimentari (78/S)'),
('Specialistiche in scienze e tecnologie agrozootecniche (79/S)'),
('Specialistiche in scienze e tecnologie dei sistemi di navigazione (80/S)'),
('Specialistiche in scienze e tecnologie della chimica industriale (81/S)'),
('Specialistiche in scienze e tecnologie per l\'ambiente e il territorio (82/S)'),
('Specialistiche in scienze economiche per l\'ambiente e la cultura (83/S)'),
('Specialistiche in scienze economico-aziendali (84/S)'),
('Specialistiche in scienze geofisiche (85/S)'),
('Specialistiche in scienze geologiche (86/S)'),
('Specialistiche in scienze pedagogiche (87/S)'),
('Specialistiche in scienze per la cooperazione allo sviluppo (88/S)'),
('Specialistiche in sociologia (89/S)'),
('Specialistiche in statistica demografica e sociale (90/S)'),
('Specialistiche in statistica economica, finanziaria ed attuariale (91/S)'),
('Specialistiche in statistica per la ricerca sperimentale (92/S)'),
('Specialistiche in storia antica (93/S)'),
('Specialistiche in storia contemporanea (94/S)'),
('Specialistiche in storia dell\'arte (95/S)'),
('Specialistiche in storia della filosofia (96/S)'),
('Specialistiche in storia medievale (97/S)'),
('Specialistiche in storia moderna (98/S)'),
('Specialistiche in studi europei (99/S)'),
('Specialistiche in tecniche e metodi per la societa dell\'informazione (100/S)'),
('Specialistiche in teoria della comunicazione (101/S)'),
('Specialistiche in teoria e tecniche della normazione e dell\'informazione giuridica (102/S)'),
('Specialistiche in teorie e metodi del disegno industriale (103/S)'),
('Specialistiche in traduzione letteraria e in traduzione tecnico-scientifica (104/S)'),
('Specialistiche nelle scienze della difesa e della sicurezza (105/S)'),
('Specialistiche nelle scienze delle professioni sanitarie della prevenzione (SNT/04/S)'),
('Specialistiche nelle scienze delle professioni sanitarie della riabilitazione (SNT/02/S)'),
('Specialistiche nelle scienze delle professioni sanitarie tecniche (SNT/03/S)'),
('Specialistiche nelle scienze infermieristiche e ostetriche (SNT/01/S)'),
('Statistica (L-41)'),
('Storia (L-42)'),
('Storia dell\'arte (LM-89)'),
('Studi europei (LM-90)'),
('Tecniche e metodi per la societa dell\'informazione (LM-91)'),
('Tecnologie per la conservazione e il restauro dei beni culturali (L-43)'),
('Teorie della comunicazione (LM-92)'),
('Teorie e metodologie dell\'e-learning e della media education (LM-93)'),
('Traduzione specialistica e interpretariato (LM-94)'),
('Urbanistica e scienze della pianificazione territoriale e ambientale (L-21 / LM-48)');